console.log(`が : ${ [... 'が'] }`);
console.log(`が : ${ [... 'が'].length } CodePoints`);
console.log(`が : ${ 'が'.length } Chars (UTF-16)`);
console.log(`が : ${ Buffer.byteLength('が', 'utf8') } Bytes (UTF-8)`);
console.log(`🏳️‍🌈 : ${ [... '🏳️‍🌈'] }`);
console.log(`🏳️‍🌈 : ${ [... '🏳️‍🌈'].length } CodePoints`);
console.log(`🏳️‍🌈 : ${ '🏳️‍🌈'.length } Chars (UTF-16)`);
console.log(`🏳️‍🌈 : ${ Buffer.byteLength('🏳️‍🌈', 'utf8') } Bytes (UTF-8)`);
console.log(`🏴󠁧󠁢󠁳󠁣󠁴󠁿 : ${ [... '🏴󠁧󠁢󠁳󠁣󠁴󠁿'] }`);
console.log(`🏴󠁧󠁢󠁳󠁣󠁴󠁿 : ${ [... '🏴󠁧󠁢󠁳󠁣󠁴󠁿'] } CodePoints`);
console.log(`🏴󠁧󠁢󠁳󠁣󠁴󠁿 : ${ '🏴󠁧󠁢󠁳󠁣󠁴󠁿'.length } Chars (UTF-16)`);
console.log(`🏴󠁧󠁢󠁳󠁣󠁴󠁿 : ${ Buffer.byteLength('🏴󠁧󠁢󠁳󠁣󠁴󠁿', 'utf8') } Bytes (UTF-8)`);
